[package]
name = "tinychain"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0"  # Error Handling
once_cell = "1.17" # Lazy Static
clap = { version = "4.2", features = ["derive"] } # Command Line Argument Parser
dashmap = "5.4"    # Concurrent Hashmap
reqwest = { version = "0.11", features = ["blocking", "json"] } # HTTP Client
axum = "0.6"        # HTTP Server
tokio = { version = "1.21", features = ["full"] } # Async Runtime
crossbeam-channel = "0.5" # A Better Channel
ethers-core = "2.0"       # Wallet
ethers-signers = "2.0"    # Wallet
log = "0.4"               # Logging
env_logger = "0.10"       # Logging
serde = { version = "1.0", features = ["derive"] } # Serializing/Deserializing
serde_json = "1.0" # Serializing/Deserializing
